name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure Git identity
        run: |
          git config --global user.email "aravind284479@gmail.com"
          git config --global user.name "aravind"

      - name: Deploy to GitHub Pages
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        run: npm run deploy
